version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: homeseek-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - homeseek-network

  auth-service:
    build:
      context: ../
      dockerfile: docker/auth-service/Dockerfile
    container_name: homeseek-auth-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ../apps/auth-service/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/homeseek
    networks:
      - homeseek-network
    volumes:
      - ../apps/auth-service:/usr/src/app/apps/auth-service
      - /usr/src/app/apps/auth-service/node_modules
      - ../uploads:/usr/src/app/uploads

  property-service:
    build:
      context: ../
      dockerfile: docker/property-service/Dockerfile
    container_name: homeseek-property-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    env_file:
      - ../apps/property-service/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/homeseek
    networks:
      - homeseek-network
    volumes:
      - ../apps/property-service:/usr/src/app/apps/property-service
      - /usr/src/app/apps/property-service/node_modules
      - ../uploads/properties:/usr/src/app/apps/property-service/uploads

  client:
    build:
      context: ../
      dockerfile: docker/client/Dockerfile
    container_name: homeseek-client
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - property-service
    networks:
      - homeseek-network

networks:
  homeseek-network:
    driver: bridge
